import type { CatalogDto, StepOptionsDto } from "../model/contracts";

export const catalogFixture: CatalogDto = {
  assemblies: [
    {
      id: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      name: "Contoso.Plugins",
      version: "1.0.0.0",
      publicKeyToken: "abcdef",
      culture: "neutral",
      isolationMode: 2,
      sourceType: 0,
      isManaged: false,
      isSystem: false,
      modifiedOn: null,
      description: "demo assembly",
    },
    {
      id: "99999999-9999-9999-9999-999999999999",
      name: "Microsoft.Crm.ObjectModel",
      version: "9.0.0.0",
      publicKeyToken: "31bf3856ad364e35",
      culture: "neutral",
      isolationMode: 2,
      sourceType: 0,
      isManaged: true,
      isSystem: true,
      modifiedOn: null,
      description: null,
    },
  ],
  types: [
    {
      id: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      assemblyId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      typeName: "Contoso.Plugins.AccountPlugin",
      name: "AccountPlugin",
      friendlyName: "Account Plugin",
      isWorkflowActivity: false,
      workflowActivityGroupName: null,
      description: null,
      isManaged: false,
      isSystem: false,
    },
    {
      id: "77777777-7777-7777-7777-777777777777",
      assemblyId: "aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa",
      typeName: "Contoso.Plugins.WorkflowActivity",
      name: "WorkflowActivity",
      friendlyName: "Workflow Activity",
      isWorkflowActivity: true,
      workflowActivityGroupName: "Contoso",
      description: null,
      isManaged: false,
      isSystem: false,
    },
    {
      id: "88888888-8888-8888-8888-888888888888",
      assemblyId: "99999999-9999-9999-9999-999999999999",
      typeName: "Microsoft.Crm.ObjectModel.SystemPlugin",
      name: "SystemPlugin",
      friendlyName: "System Plugin",
      isWorkflowActivity: false,
      workflowActivityGroupName: null,
      description: null,
      isManaged: true,
      isSystem: true,
    },
  ],
  steps: [
    {
      id: "cccccccc-cccc-cccc-cccc-cccccccccccc",
      name: "AccountPlugin: Update of account",
      pluginTypeId: "bbbbbbbb-bbbb-bbbb-bbbb-bbbbbbbbbbbb",
      messageId: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
      messageName: "Update",
      filterId: "ffffffff-ffff-ffff-ffff-ffffffffffff",
      primaryEntity: "account",
      secondaryEntity: "none",
      stage: 40,
      mode: 0,
      rank: 1,
      isEnabled: true,
      filteringAttributes: ["name", "accountnumber"],
      impersonatingUserId: null,
      impersonatingUserName: null,
      description: null,
      configuration: null,
      hasSecureConfiguration: false,
      supportedDeployment: 0,
      asyncAutoDelete: false,
      isManaged: false,
      isSystem: false,
      modifiedOn: null,
    },
  ],
  images: [
    {
      id: "dddddddd-dddd-dddd-dddd-dddddddddddd",
      stepId: "cccccccc-cccc-cccc-cccc-cccccccccccc",
      name: "PreImage",
      entityAlias: "Target",
      imageType: 0,
      attributes: ["name", "revenue"],
      messagePropertyName: "Target",
      isManaged: false,
      isSystem: false,
    },
  ],
};

export const stepOptionsFixture: StepOptionsDto = {
  messages: [{ id: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee", name: "Update" }],
  filters: [
    {
      id: "ffffffff-ffff-ffff-ffff-ffffffffffff",
      messageId: "eeeeeeee-eeee-eeee-eeee-eeeeeeeeeeee",
      primaryEntity: "account",
      secondaryEntity: "none",
      availability: 0,
    },
  ],
  users: [],
};
