#!/usr/bin/env node
// Mirrors Cursor subagents into Claude Code subagents.
//
// Source of truth: .cursor/agents/*.md
// Generated copies: .claude/agents/*.md
//
// Both tools read the same Markdown + YAML frontmatter (name, description),
// so each copy is the source file with a "generated" marker after the
// frontmatter. Relative links still resolve because both folders sit at the
// same depth.
//
// Usage:
//   node scripts/sync-agents.mjs          write .claude/agents
//   node scripts/sync-agents.mjs --check  exit 1 if .claude/agents is stale

import { existsSync, mkdirSync, readFileSync, readdirSync, rmSync, writeFileSync } from "node:fs";
import { dirname, join, relative } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const sourceDir = join(root, ".cursor", "agents");
const targetDir = join(root, ".claude", "agents");
const marker = "<!-- Generated by scripts/sync-agents.mjs from .cursor/agents/";

const check = process.argv.includes("--check");
const quiet = process.argv.includes("--quiet");

const read = (path) => readFileSync(path, "utf8").replace(/\r\n/g, "\n");
const listMarkdown = (dir) => (existsSync(dir) ? readdirSync(dir).filter((f) => f.endsWith(".md")).sort() : []);

function render(file, source) {
  const match = source.match(/^---\n[\s\S]*?\n---\n/);
  if (!match) {
    throw new Error(`.cursor/agents/${file} has no YAML frontmatter (name, description).`);
  }
  const frontmatter = match[0];
  const body = source.slice(frontmatter.length);
  return `${frontmatter}\n${marker}${file}. Edit that file, then run \`node scripts/sync-agents.mjs\`. -->\n${body}`;
}

const expected = new Map(listMarkdown(sourceDir).map((file) => [file, render(file, read(join(sourceDir, file)))]));
const stale = [];

for (const [file, content] of expected) {
  const target = join(targetDir, file);
  if (existsSync(target) && read(target) === content) continue;
  stale.push(`update ${relative(root, target)}`);
  if (!check) {
    mkdirSync(targetDir, { recursive: true });
    writeFileSync(target, content);
  }
}

// Remove copies whose Cursor source was deleted. Hand-written Claude agents
// (no marker) are left alone.
for (const file of listMarkdown(targetDir)) {
  if (expected.has(file)) continue;
  const target = join(targetDir, file);
  if (!read(target).includes(marker)) continue;
  stale.push(`remove ${relative(root, target)}`);
  if (!check) rmSync(target);
}

if (check && stale.length > 0) {
  console.error("Claude agents are out of sync with .cursor/agents:");
  for (const line of stale) console.error(`  ${line}`);
  console.error("Run: node scripts/sync-agents.mjs");
  process.exit(1);
}

if (!quiet) {
  console.log(stale.length === 0 ? "Claude agents are in sync." : stale.join("\n"));
}
